# Generated by Django 4.0.2 on 2023-12-30 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lequydonapp', '0002_thongbao'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
