# Generated by Django 4.0.2 on 2023-12-31 13:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lequydonapp', '0003_user_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lop', models.CharField(max_length=200)),
                ('siso', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
