# Generated by Django 4.0.2 on 2024-01-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lequydonapp', '0005_user_birthday_user_sdt_user_thuongtru'),
    ]

    operations = [
        migrations.CreateModel(
            name='TinTuc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
    ]
