# Generated by Django 4.0.2 on 2024-02-10 15:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lequydonapp', '0006_tintuc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tintuc',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
