# Generated by Django 4.0.2 on 2024-02-27 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lequydonapp', '0008_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaHocHetLop5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DangKyHoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Phuong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Truong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TruongVaQuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lequydonapp.quan')),
                ('truong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lequydonapp.truong')),
            ],
        ),
        migrations.CreateModel(
            name='QuanvaPhuong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phuong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lequydonapp.phuong')),
                ('quan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lequydonapp.quan')),
            ],
        ),
        migrations.CreateModel(
            name='DonTuyenSinh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100)),
                ('sdt', models.CharField(max_length=100)),
                ('hokhau', models.CharField(max_length=100)),
                ('choDK', models.CharField(max_length=100)),
                ('cccd', models.IntegerField()),
                ('is_parent', models.CharField(max_length=100)),
                ('truongtieuhoc', models.CharField(max_length=100)),
                ('tenhs', models.CharField(max_length=100)),
                ('ngaysinh', models.DateField(auto_now=True)),
                ('gioitinh', models.CharField(max_length=100)),
                ('dantoc', models.CharField(max_length=100)),
                ('tongiao', models.CharField(max_length=100)),
                ('noisinh', models.CharField(max_length=100)),
                ('madinhdanh', models.CharField(max_length=100)),
                ('diachi', models.CharField(max_length=100)),
                ('phuong', models.CharField(max_length=100)),
                ('diachithuongtru', models.CharField(max_length=100)),
                ('quanthuongtru', models.CharField(max_length=100)),
                ('phuongthuongtru', models.CharField(max_length=100)),
                ('dienchinhsach', models.CharField(max_length=100, null=True)),
                ('suckhoe', models.CharField(max_length=100)),
                ('tiengviet5', models.FloatField(max_length=100)),
                ('toan5', models.FloatField(max_length=100)),
                ('tongdiem', models.FloatField()),
                ('chungchita', models.CharField(max_length=100)),
                ('cambridge', models.IntegerField(null=True)),
                ('toefl', models.IntegerField(null=True)),
                ('pearson', models.FloatField(null=True)),
                ('hocba', models.CharField(max_length=100)),
                ('boi', models.CharField(max_length=100)),
                ('nangkhieu', models.CharField(max_length=100, null=True)),
                ('tdtt', models.CharField(max_length=100, null=True)),
                ('tntp', models.CharField(max_length=100, null=True)),
                ('tencha', models.CharField(max_length=100)),
                ('namsinhcha', models.IntegerField()),
                ('nghenghiep', models.CharField(max_length=100)),
                ('chucvu', models.CharField(max_length=100)),
                ('noicongtac', models.CharField(max_length=100)),
                ('sdtcha', models.IntegerField()),
                ('tenme', models.CharField(max_length=100)),
                ('namsinhme', models.IntegerField()),
                ('nghenghiepme', models.CharField(max_length=100)),
                ('chucvume', models.CharField(max_length=100)),
                ('noicongtacme', models.CharField(max_length=100)),
                ('sdtme', models.CharField(max_length=100)),
                ('chonlop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lequydonapp.dangkyhoc')),
                ('otp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lequydonapp.otp')),
                ('quan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lequydonapp.quan')),
                ('trinhdo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lequydonapp.dahochetlop5')),
            ],
        ),
    ]
