# Generated by Django 4.0.2 on 2024-02-27 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lequydonapp', '0009_dahochetlop5_dangkyhoc_otp_phuong_quan_truong_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dontuyensinh',
            name='otp',
        ),
    ]
