# Generated by Django 4.0.2 on 2024-02-27 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lequydonapp', '0010_remove_dontuyensinh_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
